### ISSUE TITLE
themes/siberia/layout/layout.ejs:5  ERROR

### ISSUE THREAD

**Issue by RooQs** [hpcslag/hexo-theme-siberia#1]
err: Error: /Users/rooqs/work/node_project/blog/themes/siberia/layout/layout.ejs:5
      3| <head>
      4|   <meta charset="utf-8">
   >> 5|   <%- partial('google-analytics') %>
      6|   <%
      7|   var title = page.title;
      8|

**Comment by hpcslag** [comment]
Hi, Thanks for your report that issue.

I have fixed the problem, it's because OSX added wired character to filename `%08`, and also `google-analytics` used in the wrong place.

Just goto `theme/siberia` and enter `git pull` to update.

Have a nice day.
